/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * qMessengerPreferences.java
 *
 * Created on 07.03.2010, 20:05:42
 */

package MainWindow;

import clientapp.ApplicationSettings;
import clientapp.Global;
import clientapp.Utils;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Администратор
 */
public class qMessengerPreferences extends javax.swing.JFrame {

    /** Creates new form qMessengerPreferences */
    public qMessengerPreferences() {
        initComponents();
        this.setIconImage(Global.applicationIcon);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSavePreferences = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtSavePath = new javax.swing.JTextField();
        lblSavePath = new javax.swing.JLabel();
        btnExplore = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblServerAddress = new javax.swing.JLabel();
        txtServerAddress = new javax.swing.JTextField();
        chkMinimizeOnClose = new javax.swing.JCheckBox();
        chkFullPath = new javax.swing.JCheckBox();

        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setTitle("Настройки программы");
        setResizable(false);

        btnSavePreferences.setText("Сохранить");
        btnSavePreferences.setName("btnSavePreferences"); // NOI18N
        btnSavePreferences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaveButonPress(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N

        txtSavePath.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtSavePath.setName("txtSavePath"); // NOI18N

        lblSavePath.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblSavePath.setText("Путь сохранения файлов");
        lblSavePath.setName("lblSavePath"); // NOI18N

        btnExplore.setText("Обзор...");
        btnExplore.setName("btnExplore"); // NOI18N
        btnExplore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExplore_Press(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSavePath, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(lblSavePath)
                    .addComponent(btnExplore))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblSavePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSavePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExplore)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtSavePath.setText(Global.defaultSavePath);

        jPanel2.setName("jPanel2"); // NOI18N

        lblServerAddress.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblServerAddress.setText("Адрес сервера");
        lblServerAddress.setName("lblServerAddress"); // NOI18N

        txtServerAddress.setName("txtServerAddress"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtServerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServerAddress))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblServerAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtServerAddress.setText(Global.ServAddr);

        chkMinimizeOnClose.setText("Сворачивть в трей при выходе");
        chkMinimizeOnClose.setName("chkMinimizeOnClose"); // NOI18N

        chkFullPath.setText("Выводить полный путь для пользователей");
        chkFullPath.setName("chkFullPath"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSavePreferences, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkFullPath)
                            .addComponent(chkMinimizeOnClose))
                        .addGap(123, 123, 123)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkMinimizeOnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFullPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnSavePreferences)
                .addContainerGap())
        );

        chkMinimizeOnClose.setSelected(Global.minimizeOnClose);
        chkFullPath.setSelected(Global.getFullUserPath);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButonPress(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButonPress
        if(!CheckInput()) return;
        Global.ServAddr = txtServerAddress.getText();
        Global.defaultSavePath = txtSavePath.getText();
        Global.minimizeOnClose = chkMinimizeOnClose.isSelected();
        Global.getFullUserPath = chkFullPath.isSelected();
        ApplicationSettings.saveProperties();
        Global.getUser().getScreenView().SetCloseOperation();
        this.setVisible(false);
    }//GEN-LAST:event_SaveButonPress

    private void btnExplore_Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExplore_Press
       JFileChooser chooser = new JFileChooser();
       chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
       if (JFileChooser.APPROVE_OPTION == chooser.showDialog(this, "Select"))
       {
            txtSavePath.setText(chooser.getSelectedFile().getPath());
       }
    }//GEN-LAST:event_btnExplore_Press
    public boolean CheckInput()
    {

        if(!Utils.CheckDirectoryExists(txtSavePath.getText()))
        {
            JOptionPane.showMessageDialog(this, "Путь указан неправильно", "Информация", JOptionPane.OK_OPTION);
            return false;
        }
        if(!Utils.CheckIp(txtServerAddress.getText()))
        {
            JOptionPane.showMessageDialog(this, "Адрес сервера указан неверно", "Информация", JOptionPane.OK_OPTION);
            return false;
        }

        return true;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qMessengerPreferences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExplore;
    private javax.swing.JButton btnSavePreferences;
    private javax.swing.JCheckBox chkFullPath;
    private javax.swing.JCheckBox chkMinimizeOnClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSavePath;
    private javax.swing.JLabel lblServerAddress;
    private javax.swing.JTextField txtSavePath;
    private javax.swing.JTextField txtServerAddress;
    // End of variables declaration//GEN-END:variables

}
